version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: 7.2.7-fpm-alpine3.7
    networks:
      - backend
    volumes:
      - ~/code/dev/my_project/public:/var/www/html/ 
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: httpd:2.4.41-alpine
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ~/code/dev/my_project/public:/var/www/html/
    container_name: apache
  mysql:
    image: mysql:8.0.17
    restart: always
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Project1"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    container_name: mysql
networks:
  frontend:
  backend:
volumes:
    data: